ALTER TABLE orders 
  MODIFY COLUMN date DATETIME NOT NULL,
  MODIFY COLUMN final_price DECIMAL(10,2) DEFAULT 0.00,
  ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE,
  ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
